# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226e5a57bba6ee62ef9dcb85fb6e32b28b4a9517c8a8cb8fb22102353ba56c6080a476b56bc09c032ff5efe0868e97722c4e518b5718b2bf7ef699cf1e4a9732

test:
  secret_key_base: e8b143bc1660277dba306c8452bd590063ca0b79aecf2be7c09c3bd0d677bd561e45c7dc05331f58687769a7937ffbb53fabc5872243c1e682045a943d1f9329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
