Mountain.create :name => 'Mount Everest', :image => 'http://cdn3.list25.com/wp-content/uploads/2012/11/everest.png', :height => 8848, :country => 'Nepal', :range => 'Himalayas'
Mountain.create :name => 'Mount Aconcagua', :image => 'http://cdn.list25.com/wp-content/uploads/2012/11/Aconcagua.png', :height => 6960, :country => 'Argentina', :range => 'Andes'
Mountain.create :name => 'Mount McKinley', :image => 'http://cdn2.list25.com/wp-content/uploads/2012/11/Mount-McKinley.png', :height => 6194, :country => 'Alaska', :range => 'Alaska Range'
Mountain.create :name => 'Kilmanjaro', :image => 'http://cdn2.list25.com/wp-content/uploads/2012/11/800px-Mount_Kilimanjaro.png', :height => 5895, :country => 'Tanzania', :range => 'Kilmanjaro National Park'
Mountain.create :name => 'Mount Carstensz', :image => 'http://cdn2.list25.com/wp-content/uploads/2012/11/Puncak-Jaya.png', :height => 4884, :country => 'Indonesia', :range => 'Sudirman'
Mountain.create :name => 'Mont Blanc', :image => 'http://cdn3.list25.com/wp-content/uploads/2012/11/Mont-Blanc.png', :height => 4810, :country => 'France', :range => 'Alps'
Mountain.create :name => 'Namcha Barwa', :image => 'http://cdn.list25.com/wp-content/uploads/2012/11/Namcha-Barwa.png', :height => 7660, :country => 'Tibet', :range => 'Himalayas'
Mountain.create :name => 'Bodga Peak', :image => 'http://cdn.list25.com/wp-content/uploads/2012/11/Bogda-Peak.png', :height => 5445, :country => 'China', :range => 'Tien Shan Mountains'
Mountain.create :name => 'Chimborazo', :image => 'http://cdn4.list25.com/wp-content/uploads/2012/11/Chimborazo.png', :height => 6268, :country => 'Ecuador', :range => 'Andes'
